name: Conventional Commits
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
      - edited
permissions:
  pull-requests: read
jobs:
  lint:
    name: Lint
    uses: lambchr/sre-workflows/.github/workflows/conventional-commits.yaml@d242fe98d1b75c39310b4095697ca5f5e29aeb41
    with:
      sha-from: ${{ github.event.pull_request.base.sha }}
      sha-to: ${{ github.event.pull_request.head.sha }}
