name: Conventional Commits
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
      - edited
permissions:
  pull-requests: read
jobs:
  lint:
    name: Lint
    uses: lambchr/sre-workflows/workflows/conventional-commits/conventional-commits.yaml@65959c2507b737f099eceee6b0a2d6b434eb3bde
    with:
      sha-from: ${{ github.event.pull_request.base.sha }}
      sha-to: ${{ github.event.pull_request.head.sha }}
