name: Conventional Commits
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
      - edited
permissions:
  pull-requests: read
jobs:
  lint:
    name: Lint
    uses: lambchr/sre-workflows/.github/workflows/conventional-commits.yaml@9d217f07a359c2440df5656eb61f4419e75b3b88
    with:
      sha-from: ${{ github.event.pull_request.base.sha }}
      sha-to: ${{ github.event.pull_request.head.sha }}
