name: Lint
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
      - edited
    paths:
      - modules/**
permissions:
  pull-requests: read
jobs:
  main:
    name: Validate PR Title Conventional Commit
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
