name: Terraform Module README
on:
  push:
    branches:
      - main
    paths:
      - modules/**
permissions:
  contents: write
jobs:
  update-readme:
    name: Update
    uses: lambchr/sre-workflows/.github/workflows/terraform-module-readme.yaml@07f2b015df99ef2957d8ddbd8bb4ddaef31547a5
