name: Terraform Module Release
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - main
    paths:
      - modules/**
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    name: Release
    uses: lambchr/sre-workflows/.github/workflows/terraform-module-release.yaml@9d217f07a359c2440df5656eb61f4419e75b3b88
