name: Terraform Module README
on:
  push:
    branches:
      - main
    paths:
      - modules/**
permissions:
  contents: write
jobs:
  update-readme:
    name: Update
    uses: lambchr/sre-workflows/.github/workflows/terraform-module-readme.yaml@9d217f07a359c2440df5656eb61f4419e75b3b88
