name: Terraform Module
on:
  pull_request:
    paths-ignore:
      - modules/**
permissions:
  contents: write
  pull-requests: write
jobs:
  job-status:
    name: Status
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Successful deploy
        run: |
          echo "SUCCESS"
          echo "======="
          echo "This job is checked by GitHub branch protection."
          echo "It always passes to ensure PRs without module/** file changes pass GitHub branch protection."
          exit 0
