name: Terraform Module Validate
on: pull_request
permissions:
  contents: write
  pull-requests: write
jobs:
  validate:
    name: Validate
    uses: lambchr/sre-workflows/.github/workflows/terraform-module-validate.yaml@d242fe98d1b75c39310b4095697ca5f5e29aeb41
