name: Terraform Module Release
on:
  push:
    branches:
      - main
    paths:
      - modules/**
permissions:
  contents: write
  pull-requests: write
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: ["modules/bucket", "modules/vpc-endpoint"]
    steps:
      - uses: googleapis/release-please-action@v4
        id: tag-release
        with:
          path: modules/${{ matrix.module }}
          changelog-path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: terraform-module
          monorepo-tags: true
          package-name: ${{ matrix.module }}
          skip-github-pull-request: true
